name: Setup
description: Set up Node.js, cache and install dependencies
runs:
  using: composite
  steps:
    # Requires git checkout with fetch depth 0
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install
      env:
        HUSKY_SKIP_INSTALL: 'true'
